[package]
name = "ortex"
version = "0.2.0-rc.1"
authors = []
edition = "2018"

[lib]
name = "ortex"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.37.1"
ort = { version = "2.0.0-rc.11", features = ["half"] }
ndarray = "0.17.2"
half = "2.2.1"

[features]
# ONNXRuntime Execution providers
directml = ["ort/directml"]
coreml = ["ort/coreml"]
cuda = ["ort/cuda"]
tensorrt = ["ort/tensorrt"]
